### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by shirish93** [Kraymer/flinck#11]
Congrats for the massive improvements over the weekend!

This is probably going to be harder, but would windows compatibility be a possibility at this point?

I see there are some good _pointers_ in the following SO threads:

http://stackoverflow.com/questions/1447575/symlinks-on-windows

http://stackoverflow.com/questions/26787872/how-to-create-symlinks-in-windows-using-python

**Comment by Kraymer** [comment]
Support for Windows 6.0 (Vista) symbolic links [has been introduced in python 3.2](https://docs.python.org/3/library/os.html#os.symlink), so it might well _just work_ as it is now. That requires to set the rights to create links as described [here](http://stackoverflow.com/a/26788322/5181).
I don't have a Windows environment at disposal, could you try running flinck with python 3.2+ and tell me the results ?

**Comment by Kraymer** [comment]
@shirish93 any news on that front?

**Comment by shirish93** [comment]
Working on it, haven't gotten it to work yet.

**Comment by shirish93** [comment]
So the symlink issue appears to work now (perhaps it was network-drive issue on my side). However, do I have to go to installed libraries path everytime I want to run this? I was hoping to use it as an imported module from inside python rather than a CLI, and it's such a pain to do that. I imagine it would be quite easy for you to do that? Could I request that enhancement, please?

...Also, I'm working on doing this, but for TV shows... I'll send a PR when I'm ready...

**Comment by Kraymer** [comment]
> I was hoping to use it as an imported module from inside python rather than a CLI

Seems legit : #26
