### ISSUE TITLE
Enable use as a python module

### ISSUE THREAD

**Issue by Kraymer** [Kraymer/flinck#26]
like that :

```
>>> from flinck import flinck
>>> flinck('mymovie.avi', by=('genre', 'year'))
```

**Comment by Kraymer** [comment]
@shirish93 so with latest master, following code works :

```
>>> from flinck import flinck
>>> flinck('mymovie.avi',  '-b', 'genre', '-b', 'year')
```

**Comment by shirish93** [comment]
Sweet! Can I upgrade it on pip or should I install it from here?

**Comment by Kraymer** [comment]
Not on pip yet, will be included in next release.

You need to `git pull origin` your clone to grab last state.

**Comment by shirish93** [comment]
Done, great, thanks! You might want to check if master build is working... I tried installing it directly from the repo, and it failed because of a missing 'import io' in setup.py. I plugged that in, and it was fine. Could be just me, though.

**Comment by Kraymer** [comment]
you're right i fix that now
