### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by shirish93** [Kraymer/flinck#4]
Is there any dependency that needs py27 to run?

Also, IMDB is a  _ridiculously_ large dependency to include to such a simple script (it installed at least 7 OTHER dependencies, all of which were huuuge, including Django, just to use the sqlAlchemy). Use OMDB instead.

https://github.com/dgilland/omdb.py

**Comment by Kraymer** [comment]
Fair points. I created #5 as it's two separate issues.
